### ISSUE TITLE
Option to store "closed" & "filtered" ports

### ISSUE THREAD

**Issue by gowthamsadasivam** [exitnode/nmap-sqlite-output#1]
Hello,

By default this script stores the information about the ports which all are in "open" state to the sqlite DB. Is there a way, I could store "closed" & "filtered" ports information too? Maybe tweaking the script a bit?

Thanks.

**Comment by exitnode** [comment]
Hi,

sorry for this super late answer.  If I remember right, this is not possible, sorry.
